src/main/java/it/r8/webapp/plinio/answer/AnswerListController.java
package it.r8.webapp.plinio.answer;

import java.util.List;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;

import it.r8.webapp.plinio.core.Repository;

@ManagedBean
@ApplicationScoped
public class AnswerListController {
	
	private String test;
	
	@Inject
	private Repository <Integer, Answer> Repository;

	public String getTest() {
		return test;
	}

	public void setTest(String test) {
		this.test = test;
	}

	public List<Answer> getAll(int id) {
		return Repository.getAll();
	}

}

src/main/java/it/r8/webapp/plinio/core/BaseController.java
package it.r8.webapp.plinio.core;

import java.io.IOException;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;

public abstract class BaseController extends BaseDomain<Long>{


	private static final long serialVersionUID = 1L;

	protected Map<String, String>parameters;

	@PostConstruct 
	public void postConstruct() {
		parameters=FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
		init();
	}

	public abstract void init();

	public void redirect(String pageUrl) {
		try {
			FacesContext.getCurrentInstance().getExternalContext().redirect(pageUrl);

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public Map<String, String> getParameters() {
		return parameters;
	}

	public void setParameters(Map<String, String> parameters) {
		this.parameters = parameters;
	}	
}

src/main/java/it/r8/webapp/plinio/core/IndexController.java
package it.r8.webapp.plinio.core;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean
@ViewScoped
public class IndexController extends BaseController {

	private static final long serialVersionUID = 1L;

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}

src/main/java/it/r8/webapp/plinio/login/LoginController.java
package it.r8.webapp.plinio.login;

import java.io.IOException;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import it.r8.webapp.plinio.core.Repository;

@ManagedBean
@ViewScoped
public class LoginController {
	
	@Inject
	private Repository <Integer, Login> Repository;
	String username;
	String password;
	
	public void login(){
		FacesContext context = FacesContext.getCurrentInstance();
		boolean access=false;
		List<Login> users = Repository.getAll();
		
		for(Login userReaded : users) {
			if ( this.password.equals(userReaded.getPassword()) && this.username.equals(userReaded.getUsername())) {
				context.getExternalContext().getSessionMap().put("user", username);
				try {
					context.getExternalContext().redirect("adminhome.xhtml");
				} catch (IOException e) {
					e.printStackTrace();
				}
				access=true;
			}	
		}
		
		if (!access){
			context.addMessage(null, new FacesMessage("Autenticazione Fallita ! Username o Password errati"));
		}
	}
	
	public void logout() {
    	FacesContext context = FacesContext.getCurrentInstance();
    	context.getExternalContext().invalidateSession();
        try {
			context.getExternalContext().redirect("login.xhtml");
		} catch (IOException e) {
			e.printStackTrace();
		}
    }
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}

src/main/java/it/r8/webapp/plinio/question/QuestionListController.java
package it.r8.webapp.plinio.question;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;

import it.r8.webapp.plinio.core.BaseController;
import it.r8.webapp.plinio.core.Repository;
import it.r8.webapp.plinio.data.Data;

@ManagedBean
@ViewScoped
public class QuestionListController extends BaseController {
	
private static final long serialVersionUID = 1L;
	
	@Inject
	private QuestionRepo questionRepository;
		
	@Inject
	private Repository<Integer, Data> dataRepository;
		
	private List<Question> questions;
	
	private Map<Integer, Integer> choices = new HashMap<>();
	
	@Override
	public void init() {
		Integer idSurvey = Integer.valueOf(parameters.get("idSurvey"));
		questions = questionRepository.getAllBySurvey(idSurvey);
	}
	
	public void addSurvey() {
		for(Entry<Integer, Integer> selectedChoice : choices.entrySet()) {			
			Data data = new Data();
			data.setIdQuestion(selectedChoice.getKey());
			data.setIdAnswer(Integer.valueOf(String.valueOf(selectedChoice.getValue())));
			
			dataRepository.add(data);

		}	
	}

	public boolean enableToSend() {
		return !(choices.size() == questions.size());
	}
	
	public List<Question> getQuestions() {
		return questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	public Map<Integer, Integer> getChoices() {
		return choices;
	}

	public void setChoices(Map<Integer, Integer> choices) {
		this.choices = choices;
	}
	
	public String getId(Question question) {
		return "" + System.currentTimeMillis();
	}

}

src/main/java/it/r8/webapp/plinio/survey/StatisticSurveyController.java
package it.r8.webapp.plinio.survey;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;

import it.r8.webapp.plinio.core.BaseController;

@ManagedBean
@ViewScoped
public class StatisticSurveyController  extends BaseController {
	
	private static final long serialVersionUID = 1L;
	
	private List<StatisticSurveyData> statisticsSurveyData;
	
	@Inject
	private SurveyRepo surveyRepository;
	
	@Override
	public void init() {
		Integer idSurvey = Integer.valueOf(parameters.get("idSurvey"));
		statisticsSurveyData = surveyRepository.getAllBySurvey(idSurvey);
	}
	
	public List<StatisticSurveyData> getStatisticsSurveyData() {
		return statisticsSurveyData;
	}

	public void setStatisticsSurveyDeta(List<StatisticSurveyData> statisticsSurveyData) {
		this.statisticsSurveyData = statisticsSurveyData;
	}

	public String getPieChartData(StatisticSurveyData statisticSurveyData) {
		StringBuilder stringBuilder = new StringBuilder();

		for (AnswerSelected answerSelected : statisticSurveyData.getAnswersSelected()) {
			stringBuilder.append("[");
			stringBuilder.append("'");
			stringBuilder.append(answerSelected.getText());
			stringBuilder.append("'");
			stringBuilder.append(",");
			stringBuilder.append(answerSelected.getOccurrence());
			stringBuilder.append("]");
			stringBuilder.append(",");
		}
		
		return stringBuilder.toString();
	}
}

src/main/java/it/r8/webapp/plinio/survey/SurveyListController.java
package it.r8.webapp.plinio.survey;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;

@ManagedBean
@ViewScoped
public class SurveyListController {

private String test;
	
	@Inject
	private SurveyRepo surveyRepository;

	public String getTest() {
		return test;
	}

	public void setTest(String test) {
		this.test = test;
	}

	public List<Survey> getSurveys() {
		return surveyRepository.getAll();
	}

}

src/main/webapp/pages/admin/adminhome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon"
		href="#{resource['images/Logo-MAV.ico']}" />
		
	<style type="text/css">
		.fa-pie-chart {
			color: #808184;
		}
	</style>
</h:head>
<h:body style="background: #444">
	<b:image library="images" name="admin.png" style="width:1.4%" />
	<b:image library="images" name="diagram.png" style="width:1.4%" />
	<h:panelGroup rendered="#{not empty user}"
		style="margin-top: 10em; color:#808184 ; background:#444 ">




		<Strong>Benvenuto, #{user}</Strong>
		<h:form>
			<h:commandButton value="logout" action="#{loginController.logout}" />
		</h:form>
	</h:panelGroup>


	<h:form>
		<b:row>

			<b:image library="images" name="Logo-MAV.png"
				class="img-responsive center-block"
				style="width:18% ;margin-top: 6em" />


		</b:row>
	</h:form>

	<b:row style="text-align:center; margin-top: 3em">
		<b:column>
			<b:container offset="2">
				<b:pillLinks>
					<ui:repeat var="survey" value="#{surveyListController.surveys}"
						varStatus="loop">
						<b:navLink value="#{survey.typology}"
							style="font-size: 1.3em; font-weight: bold;color: #c8c8c8"
							href="http://localhost:8080/plinio/pages/admin/piechart.xhtml?idSurvey=#{survey.id}"
							icon-awesome="pie-chart" icon-align="right"/>
					</ui:repeat>
				</b:pillLinks>
			</b:container>
		</b:column>
	</b:row>


</h:body>
</html>

src/main/webapp/pages/admin/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon"
		href="#{resource['images/Logo-MAV.ico']}" />
</h:head>
<h:body style="background: #444">
	<h:form>
		<b:row>
		
		<b:image library="images" name="Logo-MAV.png" 
				class="img-responsive center-block" style="width:18% ;margin-top: 6em" />
		
			
		</b:row>
		
		
		
		
		
		
		
		
		
<b:row style="text-align:center; margin-top: 3em">
			<b:column>

  	<b:container layout="fluid" style="width: 500px" >
    	<b:panel title="LOGIN" look="primary">
    		<b:row>
        		<b:column medium-screen="3">
          			<h:outputText value="Username:" for="username" />
        		</b:column>
        		<b:column medium-screen="6">
    				<b:inputText id="username" value="#{loginController.username}" >   
    					<f:facet name="prepend">
        					<b:icon name="user" />
        				</f:facet>
   					</b:inputText>
    			</b:column>
			</b:row>
			<b:row>
        		<b:column medium-screen="3">
          			<h:outputText value="Password:" for="password" />
        		</b:column>
        		<b:column medium-screen="6">
    				<b:inputSecret id="password" value="#{loginController.password}" >
    					<f:facet name="prepend">
        					<b:iconAwesome name="key" />
        				</f:facet>
   					</b:inputSecret>
   				</b:column>	
   			</b:row>		
   			<b:row>
        		<b:column span="3" offset="3">
    				<b:commandButton value="Login" action="#{loginController.login}" look="primary" style="width:100%"/>
    			</b:column>	
   			</b:row>		
   			<h:messages globalOnly="true" style="color:red;margin:8px;" />
	</b:panel>

  </b:container>
  </b:column>
  </b:row>
  
	</h:form>
</h:body>
</html>	

src/main/webapp/pages/admin/piechart.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon"
		href="#{resource['images/Logo-MAV.ico']}" />
	<style>
body {
	position: relative;
	margin: 0;
	padding: 0;
}

.section {
	padding-top: 50px;
	height: 100vh;
	color: #fff;
}

.section-1 {
	background-color: cadetblue;
}

.section-2 {
	background-color: rosybrown;
}

.section-3 {
	background-color: deepskyblue;
}

#section1 {
	background-color: #1E88E5;
}

#section2 {
	background-color: #673ab7;
}

#section3 {
	background-color: #ff9800;
}

#section41 {
	background-color: #00bcd4;
}

#section42 {
	background-color: #009688;
}
</style>

	<script type="text/javascript"
		src="https://www.gstatic.com/charts/loader.js"></script>

	<script type="text/javascript">
   					google.charts.load("current", {packages:["corechart"]});
    				google.charts.setOnLoadCallback(drawChart);
    				function drawChart() {
    					<ui:repeat var="statisticSurveyData"
    						value="#{statisticSurveyController.statisticsSurveyData}"
    						varStatus="loop">

        					var data_#{loop.index} = google.visualization.arrayToDataTable([
            					['Answer', 'Value'],
            					#{statisticSurveyController.getPieChartData(statisticSurveyData)}
            				    ]);

            					var options = {
            						legend: {textStyle: {color: 'white', fontSize: 20}},
            						titlePosition: 'none',
            						is3D: true,
                					'backgroundColor': 'transparent'
                				};

               					var chart_#{loop.index} = new google.visualization.PieChart(document.getElementById('chart_' + #{loop.index}));
                				chart_#{loop.index}.draw(data_#{loop.index}, options);
    					</ui:repeat>
      				}
    			</script>

</h:head>
<h:body>
	<h:form>
	<style>
    	div.scroll {
      		position: relative;
      		height:200px;
      		overflow:scroll;
      		width: 98%;
    	}
  	</style>
		<b:growl id="growlMsg" globalOnly="true" placement-from="bottom"
			showDetail="false" showSummary="true" allowDismiss="true"
			delay="10000" escape="true" />

		<b:navBar id="nb" brand-img="http://localhost:8080/plinio/resources/images/Logo-MAV.png" brand-img-style="width:70px; margin-top:-20px;" brand-href="http://localhost:8080/plinio/pages/admin/adminhome.xhtml" fixed="top">
			
			<b:navbarLinks>
				<ui:repeat var="statisticsSurveyData"
					value="#{statisticSurveyController.statisticsSurveyData}"
					varStatus="loop">
					<b:navLink value="#{loop.index + 1}"
						href="##{statisticsSurveyData.id}" />
				</ui:repeat>
			</b:navbarLinks>
		</b:navBar>

		<ui:repeat var="statisticSurveyData"
			value="#{statisticSurveyController.statisticsSurveyData}"
			varStatus="loop">
			<div id="#{statisticSurveyData.question.id}"
				class="container-fluid section section-#{(loop.index % 3) + 1}">
			<b:container fluid="true" >	
				<h1 align="center">#{statisticSurveyData.question.text}</h1>
				<div id="chart_#{loop.index}" style="margin: 0 auto; width: 1400px; height: 600px; "></div>
			</b:container>	
			</div>
		</ui:repeat>
		 <b:scrollSpy target="nb" smooth="true" selectionListener="#{spy}" update="growlMsg"/>
	</h:form>
</h:body>
</html>

src/main/webapp/pages/credits.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon"
		href="#{resource['images/Logo-MAV.ico']}" />
</h:head>
<meta http-equiv="refresh" content="20;URL=index1.xhtml"/>
<h:body style="background: #444">
	<h:form>
		<b:row>
		
		<b:image library="images" name="logoteam.png" 
				class="img-responsive center-block" style="width:14% ;margin-top: 8em" />
		<b:image library="images" name="logoprotom.png" 
				class="img-responsive center-block" style="width:14% ;margin-top: 3em" />
		</b:row>
	</h:form>
	<b:row style="text-align:center; margin-top: 3em; color: #000000; font-size:20px">
		<b:column>
			<b:container offset="2">
			<h:outputText value="Developers : "/> <br></br><br></br>
			<h:outputText value="Gennaro Conza "/> <br></br>
			<h:outputText value="Luigi Criscuolo "/> <br></br>
			<h:outputText value="Maria De Rosa"/> <br></br>
			<h:outputText value="Marco Pellegrino "/><br></br>
			<h:outputText value="Davide Piepoli "/><br></br>
			</b:container>
		</b:column>
	</b:row>
			
</h:body>
</html>
				

src/main/webapp/pages/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon" href="#{resource['images/Logo-MAV.ico']}"/>
	
	
	<nav class="navbar navbar-inverse"  >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="index.xhtml">Home</a></li>
        <li><a href="users/questions-list.xhtml?idSurvey=3">Adulti</a></li>
        <li><a href="users/questions-list.xhtml?idSurvey=4">Gruppi</a></li> 
        <li><a href="users/questions-list.xhtml?idSurvey=2">Ragazzi</a></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
</h:head>
<h:body style="overflow: hidden;     background-color: #920403" >
	<h:form>
	<b:image library="images" name="c.jpg" 
				class="img-responsive center-block" style="width:61% ;margin-top: -5em" />		
		
		
		<b:column>
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=3')}">
						<b:image library="images" name="button1.png"
						  style="width:80px;margin-top:-592px; margin-left: -240px" />
					</b:commandButton>
				</div>
		</b:column>
				
		<b:column>
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=4')}">
						<b:image library="images" name="button2.png"
						  style="width:80px;margin-top:-660px;margin-left: 18px" />
					</b:commandButton>
				</div>
		</b:column>
		
		<b:column>
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=2')}">
						<b:image library="images" name="button3.png"
						  style="width:80px;margin-top:-728px;margin-left: 270px" />
					</b:commandButton>
				</div>
		</b:column>
		
		
		
		
	</h:form>
	
	
	
	
	
	
	
	
	
	
	
	
</h:body>
</html>

src/main/webapp/pages/home1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon"
		href="#{resource['images/Logo-MAV.ico']}" />
</h:head>
<h:body style="background: #444">
	<h:form>
		<b:row>
		
		<b:image library="images" name="Logo-MAV.png" 
				class="img-responsive center-block" style="width:18% ;margin-top: 6em" />
		
			
		</b:row>
		<b:row style="text-align:center; margin-top: 3em">
			<b:column>
				<b:container offset="2" span="4" style="padding: 4em 0 4em 0; background: #FFF; border-radius: 20em 1em 20em 1em ; width:870px">
					<b:commandButton look="link"
						 actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=3')}">
						<b:image library="images" name="button1.png" style="width:120px" />
					</b:commandButton>

					<b:commandButton look="link"
						actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=4')}">
						<b:image library="images" name="button2.png" style="width:120px"/>
					</b:commandButton>
					
					<b:commandButton look="link"
						actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=2')}">
						<b:image library="images" name="button3.png" style="width:120px"/>
					</b:commandButton>
				</b:container>
			</b:column>

		</b:row>
	</h:form>
</h:body>
</html>

src/main/webapp/pages/homeita.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon" href="#{resource['images/Logo-MAV.ico']}"/>
</h:head>
<h:body style="overflow: hidden;     background-color: #920403" >
	<h:form>
	<b:image library="images" name="sfondo2.jpg" 
				class="img-responsive center-block" style="width:61% ;margin-top: -5em" />		
		
		
		<b:column>
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=1')}">
						<b:image library="images" name="button1.png"
						  style="width:100px;margin-left: -300px;margin-top:-542px" />
					</b:commandButton>
				</div>
		</b:column>
				
		<b:column>
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=1')}">
						<b:image library="images" name="button2.png"
						  style="width:100px;margin-top:-600px;margin-left: 18px" />
					</b:commandButton>
				</div>
		</b:column>
		
		<b:column>
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=1')}">
						<b:image library="images" name="button3.png"
						  style="width:100px;margin-top:-663px;margin-left: 330px" />
					</b:commandButton>
				</div>
		</b:column>
		
		
		
		
	</h:form>
</h:body>
</html>

src/main/webapp/pages/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>MAV Ercolano | Museo archeologico virtuale</title>
	<link rel="shortcut icon" type="image/x-icon" href="#{resource['images/Logo-MAV.ico']}"/>
</h:head>
<h:body style="overflow: hidden;     background-color: #920403" >
	<b:row style="background: #a61f1f">
		<b:column offset="3" span="6" style="background: #920403">
		</b:column>
	</b:row>
		<h:form>
			<b:row>
			<b:image library="images" name="c.jpg" 
				class="img-responsive center-block" style="width:61% ;margin-top: -5em" />
				<b:column>
				<div>
					<b:commandButton look="link"
						 actionListener="#{indexController.redirect('home.xhtml')}">
						<b:image library="images" name="It.png"
							 class="img-responsive center-block" style="width:73px;margin-top:-321px ;margin-left: 607px" />
					</b:commandButton>
					</div>
				</b:column>
				
				<b:column>
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=1')}">
						<b:image library="images" name="Uk.png"
						  style="width:71px;margin-top:-624px;margin-left: 135px" />
					</b:commandButton>
					</div>
				</b:column>
				
				<b:column >
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=9')}">
						<b:image library="images" name="Es.png"
							 style="width:71px;margin-top:-696px;margin-left: -362px " />
					</b:commandButton>
					</div>
				</b:column>
				
				<b:column >
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=7')}">
						<b:image library="images" name="Fr.png"
							 style="width:74px ;margin-top:-758px;margin-left: -194px" />
					</b:commandButton>
					</div>
				</b:column>
				
				<b:column >
				<div>
					<b:commandButton look="link"
						class="img-responsive center-block" actionListener="#{indexController.redirect('users/questions-list.xhtml?idSurvey=8')}">
						<b:image library="images" name="Ge.png"
							 style="width:77px;margin-top:-828px;margin-left: 303px" />
					</b:commandButton>
					</div>
				</b:column>
			</b:row>
		</h:form>
</h:body>
</html>